name: Docker Build and Push

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Upgrade Node.js to v20
        uses: actions/setup-node@v2
        with:
          node-version: '20'
      
      - name: Debug Logging
        run: |
          echo "Docker Hub Username: ${{ secrets.PRAGATISAWALIYA }}"
          echo "Docker Hub PAT: ${{ secrets.DCKR_PAT_IFhG55AECVN_0amKRaNEj30l1Lo }}"

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.PRAGATISAWALIYA }}
          password: ${{ secrets.DCKR_PAT_IFhG55AECVN_0amKRaNEj30l1Lo }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: |
          docker buildx create --name mybuilder
          docker buildx use mybuilder
          docker buildx inspect --bootstrap
          docker buildx build --platform linux/amd64,linux/arm64 -t pragatisawaliya/chat_app:latest .

      - name: Push Docker image
        run: docker push pragatisawaliya/chat_app:latest
