name: CI/CD for React App

on:
  push:
    branches: [master]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build_and_deploy_client:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Adjust the version as needed

      - name: Clean cache
        run: npm cache clean --force

      - name: Install dependencies for client
        working-directory: ./client
        run: |
          npm ci
          npm run build

      - name: Deploy client to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: gh-pages
          folder: client/build

  build_and_deploy_server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Adjust the version as needed

      - name: Clean cache
        run: npm cache clean --force

      - name: Install dependencies for server
        working-directory: ./server
        run: |
          npm ci
          npm run build

      # Add deployment step for server if needed

      # Note: Deploying server to GitHub Pages is not typical,
      # consider using a different hosting service for the server.

# Optionally, you may want to combine both client and server jobs into one workflow.
# This would be useful if the server and client are tightly coupled or share some configuration.

# jobs:
#   build_and_deploy:
#     runs-on: ubuntu-latest
#     needs: [build_and_deploy_client, build_and_deploy_server]
#     steps:
#       - name: Merge artifacts or perform any necessary steps
#         run: echo "Merge artifacts or additional steps here"

