name: CI/CD for React App

on:
  push:
    branches: [master]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  builds_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Adjust the version as needed
          
      - name: Clean cache
        run: npm cache clean --force
        
      - name: Install dependencies for client
        working-directory: ./client
        run: |
          npm ci
          # Modify the build command to exclude treating warnings as errors
          npm run build -- --no-warnings
          
      - name: Deploy client to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: gh-pages
          folder: client/build

      - name: Install dependencies for server
        working-directory: ./server
        run: |
          npm ci
          # Modify the build command to exclude treating warnings as errors
          npm run build -- --no-warnings
      # Add deployment step for server if needed

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: gh-pages
          folder: server/build
